### ISSUE TITLE
bad version management?

### ISSUE THREAD

**Issue by niksfirefly** [jasonfb/nondestructive_migrations#6] opened 2015-02-04 15:24 UTC
Data migration version is written to default AR schema table due
to migration method
record_version_state_after_migrating(version)
where 
ActiveRecord::SchemaMigration.create!(:version => version.to_s)
save version number to schema_migrations.
I override your dependencies task and now things works like expected
```ruby
Rake::Task["data:data_migration_dependencies"].clear
namespace :data do
  task :data_migration_dependencies => :environment do
    require 'nondestructive_migrations'
    # setup temporary schema migrations table name
    ActiveRecord::Base.schema_migrations_table_name = 'data_migrations'
  end
end
```

**Comment by jasonfb** [comment] 2015-03-02 13:31
Hey sorry about this Version 1.0 works with Rails 3 and version 1.1 works with Rails 4 -- as you said, if yo try to use version 1.0 with Rails 4, it will put timestamps into the schema_migrations table instead of data_migrations

**Comment by mseelig** [comment] 2015-12-14 21:39
I am seeing null values in the data_migrations table after running data:migrate, I'm using Rails 4 and version 1.1 of the the gem.

**Comment by jasonfb** [comment] 2015-12-15 02:09
Spam detection software, running on the system "mail2.hsphere.cc", has
identified this incoming email as possible spam.  The original message
has been attached to this so you can view it (if it isn't spam) or label
similar future email.  If you have any questions, see
the administrator of that system for details.

Content preview:  Hmmm ... You mean null values in the timestamp field in the
   data_migrations table ? That is strange, I have never come across that. Please
   specify exactly which version of Rails 4 and I will try to reproduce [...]
   

Content analysis details:   (5.0 points, 5.0 required)

 pts rule name              description
---- ---------------------- --------------------------------------------------
 2.4 HTML_IMAGE_ONLY_20     BODY: HTML: images with 1600-2000 bytes of words
 0.0 HTML_MESSAGE           BODY: HTML included in message
 2.5 MIME_QP_LONG_LINE      RAW: Quoted-printable line longer than 76 chars
 0.1 RDNS_NONE              Delivered to trusted network by a host with no rDNS

The original message was not completely plain text, and may be unsafe to
open with some email clients; in particular, it may contain a virus,
or confirm that your address can receive spam.  If you wish to view
it, it may be safer to save it to a file and open it with an editor.


Received: from unknown (HELO ?100.77.57.222?) (jason@datatravels.com@70.208.74.184)
  (de-)crypted with TLSv1: DHE-RSA-AES256-SHA [256/256] DN=unknown
  by mail2.hsphere.cc with ESMTPSAM; 15 Dec 2015 02:09:04 -0000
X-Originating-IP: 70.208.74.184
Content-Type: multipart/alternative; boundary=Apple-Mail-6C5DF6D4-F40C-4C75-BE4E-9BC0AF283291
Content-Transfer-Encoding: 7bit
From: Jason Fleetwood-Boldt <jason@datatravels.com>
Mime-Version: 1.0 (1.0)
Subject: Re: [nondestructive_migrations] bad version management? (#6)
Date: Mon, 14 Dec 2015 21:07:24 -0500
References: <jasonfb/nondestructive_migrations/issues/6@github.com> <jasonfb/nondestructive_migrations/issues/6/164568010@github.com>
In-Reply-To: <jasonfb/nondestructive_migrations/issues/6/164568010@github.com>
To: jasonfb/nondestructive_migrations <reply@reply.github.com>
Message-Id: <64814C60-C461-43BB-82FF-6CE84D56ECCE@datatravels.com>
X-Mailer: iPhone Mail (13C75)


--Apple-Mail-6C5DF6D4-F40C-4C75-BE4E-9BC0AF283291
Content-Type: text/plain;
	charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hmmm ... You mean null values in the timestamp field in the data_migrations t=
able ?=20

That is strange, I have never come across that.

Please specify exactly which version of Rails 4 and I will try to reproduce

Sent from my iPhone

> On Dec 14, 2015, at 4:39 PM, Mark Seelig <notifications@github.com> wrote:=

>=20
> I am seeing null values in the data_migrations table after running data:mi=
grate, I'm using Rails 4 and version 1.1 of the the gem.
>=20
> =E2=80=94
> Reply to this email directly or view it on GitHub.
>=20

--Apple-Mail-6C5DF6D4-F40C-4C75-BE4E-9BC0AF283291
Content-Type: text/html;
	charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charset=3D=
utf-8"></head><body dir=3D"auto"><div>Hmmm ... You mean null values in the t=
imestamp field in the data_migrations table ?&nbsp;</div><div id=3D"AppleMai=
lSignature"><br></div><div id=3D"AppleMailSignature">That is strange, I have=
 never come across that.</div><div id=3D"AppleMailSignature"><br></div><div i=
d=3D"AppleMailSignature">Please specify exactly which version of Rails 4 and=
 I will try to reproduce</div><div id=3D"AppleMailSignature"><br>Sent from m=
y iPhone</div><div><br>On Dec 14, 2015, at 4:39 PM, Mark Seelig &lt;<a href=3D=
"mailto:notifications@github.com">notifications@github.com</a>&gt; wrote:<br=
><br></div><blockquote type=3D"cite"><div><p>I am seeing null values in the d=
ata_migrations table after running data:migrate, I'm using Rails 4 and versi=
on 1.1 of the the gem.</p>

<p style=3D"font-size:small;-webkit-text-size-adjust:none;color:#666;">=E2=80=
=94<br>Reply to this email directly or <a href=3D"https://github.com/jasonfb=
/nondestructive_migrations/issues/6#issuecomment-164568010">view it on GitHu=
b</a>.<img alt=3D"" height=3D"1" src=3D"https://github.com/notifications/bea=
con/AADmeuICqfydDOEeKYquNsKQXchKGMIKks5pPy6HgaJpZM4Dbok2.gif" width=3D"1"></=
p>
<div itemscope=3D"" itemtype=3D"http://schema.org/EmailMessage">
<div itemprop=3D"action" itemscope=3D"" itemtype=3D"http://schema.org/ViewAc=
tion">
  <link itemprop=3D"url" href=3D"https://github.com/jasonfb/nondestructive_m=
igrations/issues/6#issuecomment-164568010">
  <meta itemprop=3D"name" content=3D"View Issue">
</div>
<meta itemprop=3D"description" content=3D"View this Issue on GitHub">
</div>
</div></blockquote></body></html>=

--Apple-Mail-6C5DF6D4-F40C-4C75-BE4E-9BC0AF283291--

**Comment by jasonfb** [comment] 2016-09-01 20:24
Sorry didn't see this. Which Rails 4 did you see this symptom on?

**Comment by jasonfb** [comment] 2016-09-01 20:27
@mseelig -- version 1.0 has been tested against Rails 3 and version 1.1 has been tested against Rails 4 and 4.1. However, I have not yet tested this against Rails 4.2 or Rails 5. Please advise which version of Rails you were using when left the comment on Dec 14, 2015

**Comment by jasonfb** [comment] 2016-09-01 20:30
Closing because it is so old; please re-file if can be reproduced.

**Closed by jasonfb** 2016-09-01 20:30 UTC
